# Generated by Django 5.0.1 on 2025-06-06 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_add_uniqueness_to_phone_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='teacher_compensated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='academiclevel',
            name='category',
            field=models.CharField(choices=[('PRIMARY', 'ابتدائي'), ('MIDDLE', 'متوسط'), ('HIGH', 'ثانوي')], max_length=50),
        ),
        migrations.AlterField(
            model_name='group',
            name='session_day',
            field=models.IntegerField(choices=[(0, 'الاثنين'), (1, 'الثلاثاء'), (2, 'الأربعاء'), (3, 'الخميس'), (4, 'الجمعة'), (5, 'السبت'), (6, 'الأحد')]),
        ),
    ]
