# Generated by Django 5.2.2 on 2025-06-06 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_update_session_compensation'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='card_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
