# Generated by Django 5.0.1 on 2025-06-06 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('school_app', '0006_alter_group_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the action.')),
                ('action_type', models.CharField(help_text="Type of action performed (e.g., 'created_student', 'deleted_group').", max_length=100)),
                ('details', models.TextField(blank=True, help_text='Detailed description of the action.')),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of the related object.', null=True)),
                ('related_object_repr', models.CharField(blank=True, help_text='String representation of the related object, in case it gets deleted.', max_length=255)),
                ('content_type', models.ForeignKey(blank=True, help_text='Content type of the related object.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action. Null if system generated.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-action_time'],
            },
        ),
    ]
