# Generated by Django 5.0.1 on 2025-06-06 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0007_actionlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='teacher_paid_for_session',
        ),
    ]
