# Generated by Django 5.0.1 on 2025-06-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0008_remove_attendance_teacher_paid_for_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionlog',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='actionlog',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='actionlog',
            name='related_object_repr',
        ),
        migrations.RemoveField(
            model_name='actionlog',
            name='user',
        ),
        migrations.AddField(
            model_name='actionlog',
            name='object_name',
            field=models.CharField(blank=True, help_text='Name of the teacher, group, or session affected.', max_length=255),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='action_type',
            field=models.CharField(help_text="Type of action performed (e.g., 'teacher_added', 'group_deleted').", max_length=100),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='details',
            field=models.TextField(blank=True, help_text='Brief description of the event.'),
        ),
    ]
