# Generated by Django 5.0.1 on 2025-06-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0009_remove_actionlog_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='excused_absence',
            field=models.BooleanField(default=False),
        ),
    ]
