# Generated by Django 5.0.1 on 2025-06-09 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0010_attendance_excused_absence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='action_type',
            field=models.CharField(choices=[('student_created', 'تم إنشاء حساب طالب'), ('student_updated', 'تم تحديث بيانات طالب'), ('student_enrolled', 'تم تسجيل طالب في فوج'), ('teacher_added', 'تمت إضافة مدرس'), ('teacher_updated', 'تم تحديث بيانات مدرس'), ('group_created', 'تم إنشاء فوج جديد'), ('group_updated', 'تم تحديث بيانات فوج'), ('session_created', 'تم إنشاء حصة جديدة'), ('session_attendance_recorded', 'تم تسجيل حضور وغياب لحصة'), ('payment_recorded', 'تم تسجيل دفعة مالية'), ('user_login', 'تم تسجيل دخول مستخدم'), ('user_logout', 'تم تسجيل خروج مستخدم'), ('unknown_action', 'إجراء غير معروف')], default='unknown_action', help_text='Type of action performed.', max_length=100),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='details',
            field=models.TextField(blank=True, help_text='Additional details about the event.'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='object_name',
            field=models.CharField(blank=True, help_text='Name or ID of the affected object (student, group, etc.).', max_length=255),
        ),
    ]
