# Generated by Django 5.0.1 on 2025-06-09 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0011_alter_actionlog_action_type_alter_actionlog_details_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academiclevel',
            options={'verbose_name': 'المستوى الدراسي', 'verbose_name_plural': 'المستويات الدراسية'},
        ),
        migrations.AlterModelOptions(
            name='actionlog',
            options={'ordering': ['-action_time'], 'verbose_name': 'سجل إجراء', 'verbose_name_plural': 'سجلات الإجراءات'},
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'سجل حضور', 'verbose_name_plural': 'سجلات الحضور'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'فوج', 'verbose_name_plural': 'الأفواج'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'حصة', 'verbose_name_plural': 'الحصص'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'طالب', 'verbose_name_plural': 'الطلاب'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'مادة دراسية', 'verbose_name_plural': 'المواد الدراسية'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'مدرس', 'verbose_name_plural': 'المدرسون'},
        ),
        migrations.AddField(
            model_name='group',
            name='created_sessions_until',
            field=models.DateField(blank=True, null=True, verbose_name='تم إنشاء الحصص حتى تاريخ'),
        ),
        migrations.AddField(
            model_name='group',
            name='is_continuous',
            field=models.BooleanField(default=False, verbose_name='فوج مستمر (تُنشأ الحصص أسبوعياً تلقائياً)'),
        ),
        migrations.AlterField(
            model_name='academiclevel',
            name='category',
            field=models.CharField(choices=[('PRIMARY', 'ابتدائي'), ('MIDDLE', 'متوسط'), ('HIGH', 'ثانوي')], max_length=50, verbose_name='الفئة'),
        ),
        migrations.AlterField(
            model_name='academiclevel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='action_time',
            field=models.DateTimeField(auto_now_add=True, help_text='وقت حدوث الإجراء.', verbose_name='وقت الإجراء'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='action_type',
            field=models.CharField(choices=[('student_added', 'إنشاء حساب طالب'), ('student_updated', 'تحديث بيانات طالب'), ('student_enrolled', 'تسجيل طالب في فوج'), ('student_deleted', 'حذف طالب'), ('teacher_added', 'إضافة مدرس'), ('teacher_updated', 'تحديث بيانات مدرس'), ('teacher_deleted', 'حذف مدرس'), ('group_added', 'إنشاء فوج جديد'), ('group_updated', 'تحديث بيانات فوج'), ('group_deleted', 'حذف فوج'), ('session_added', 'إنشاء حصة'), ('session_updated', 'تحديث بيانات حصة'), ('session_deleted', 'حذف حصة'), ('attendance_recorded', 'تسجيل حضور وغياب'), ('payment_recorded', 'تسجيل دفعة مالية'), ('registration_fee_paid', 'دفع رسوم التسجيل'), ('group_session_payment_processed', 'تسجيل دفعات حصص فوج'), ('teacher_payment_processed', 'دفع مستحقات مدرس'), ('user_login', 'تسجيل دخول مستخدم'), ('user_logout', 'تسجيل خروج مستخدم'), ('report_generated', 'إنشاء تقرير'), ('unknown_action', 'إجراء غير معروف')], default='unknown_action', help_text='نوع الإجراء الذي تم تنفيذه.', max_length=100, verbose_name='نوع الإجراء'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='details',
            field=models.TextField(blank=True, help_text='تفاصيل إضافية حول الحدث.', verbose_name='التفاصيل'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='object_name',
            field=models.CharField(blank=True, help_text='اسم أو معرف الكائن المتأثر (طالب، فوج، إلخ).', max_length=255, verbose_name='اسم الكائن'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='excused_absence',
            field=models.BooleanField(default=False, verbose_name='غياب مبرر'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='present',
            field=models.BooleanField(default=True, verbose_name='حاضر'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.session', verbose_name='الحصة'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.student', verbose_name='الطالب'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student_absent_and_forced_paid',
            field=models.BooleanField(default=False, verbose_name='الطالب غائب والدفع إجباري'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student_paid_for_session',
            field=models.BooleanField(default=False, verbose_name='الطالب دفع للحصة'),
        ),
        migrations.AlterField(
            model_name='group',
            name='academic_levels',
            field=models.ManyToManyField(to='school_app.academiclevel', verbose_name='المستويات الدراسية المتوافقة'),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم الفوج'),
        ),
        migrations.AlterField(
            model_name='group',
            name='price_per_4_sessions',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر لكل 4 حصص'),
        ),
        migrations.AlterField(
            model_name='group',
            name='session_day',
            field=models.IntegerField(choices=[(0, 'الاثنين'), (1, 'الثلاثاء'), (2, 'الأربعاء'), (3, 'الخميس'), (4, 'الجمعة'), (5, 'السبت'), (6, 'الأحد')], verbose_name='يوم الحصة'),
        ),
        migrations.AlterField(
            model_name='group',
            name='session_duration',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=4, verbose_name='مدة الحصة (ساعات)'),
        ),
        migrations.AlterField(
            model_name='group',
            name='session_start_time',
            field=models.TimeField(verbose_name='وقت بداية الحصة'),
        ),
        migrations.AlterField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(blank=True, to='school_app.student', verbose_name='الطلاب المسجلون'),
        ),
        migrations.AlterField(
            model_name='group',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_app.subject', verbose_name='المادة'),
        ),
        migrations.AlterField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.teacher', verbose_name='المدرس'),
        ),
        migrations.AlterField(
            model_name='session',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='session',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='المدة (ساعات)'),
        ),
        migrations.AlterField(
            model_name='session',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='school_app.group', verbose_name='الفوج'),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.TimeField(verbose_name='وقت البدء'),
        ),
        migrations.AlterField(
            model_name='session',
            name='teacher_attended',
            field=models.BooleanField(blank=True, null=True, verbose_name='حضور المدرس'),
        ),
        migrations.AlterField(
            model_name='session',
            name='teacher_compensated',
            field=models.BooleanField(default=False, verbose_name='تم تعويض المدرس'),
        ),
        migrations.AlterField(
            model_name='student',
            name='academic_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_app.academiclevel', verbose_name='المستوى الدراسي'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_day',
            field=models.IntegerField(verbose_name='يوم الميلاد'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_month',
            field=models.IntegerField(verbose_name='شهر الميلاد'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_year',
            field=models.IntegerField(verbose_name='سنة الميلاد'),
        ),
        migrations.AlterField(
            model_name='student',
            name='card_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='رقم البطاقة'),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='الاسم الأول'),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_phone',
            field=models.CharField(max_length=20, verbose_name='رقم هاتف الولي'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='اللقب'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='رقم هاتف الطالب'),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_fee_paid',
            field=models.BooleanField(default=False, verbose_name='رسوم التسجيل مدفوعة'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم المادة'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='الاسم الأول'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='اللقب'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_app.subject', verbose_name='المادة الأساسية'),
        ),
    ]
