# Generated by Django 5.2.3 on 2025-06-10 10:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0012_alter_academiclevel_options_alter_actionlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='prepaid_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='رصيد مدفوع مقدماً'),
        ),
    ]
