# Generated by Django 5.0.1 on 2025-08-13 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0013_add_prepaid_balance_to_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="students",
        ),
    ]
