# Generated by Django 5.0.1 on 2025-08-13 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0014_remove_group_students"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enrollment_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="تاريخ التسجيل في الفوج"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school_app.group",
                        verbose_name="الفوج",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school_app.student",
                        verbose_name="الطالب",
                    ),
                ),
            ],
            options={
                "verbose_name": "تسجيل طالب في فوج",
                "verbose_name_plural": "تسجيلات الطلاب في الأفواج",
                "unique_together": {("student", "group")},
            },
        ),
        migrations.AddField(
            model_name="group",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                through="school_app.StudentGroup",
                to="school_app.student",
                verbose_name="الطلاب المسجلون",
            ),
        ),
    ]
