# Generated by Django 5.0.1 on 2025-08-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0015_studentgroup_group_students"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="teacher_attended",
            field=models.BooleanField(default=True, verbose_name="حضور المدرس"),
        ),
    ]
