# Generated by Django 5.0.1 on 2025-08-19 23:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0017_full_name_refactor"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="teacher_payment_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="المبلغ المدفوع للمدرس",
            ),
        ),
    ]
