# Generated by Django 5.0.1 on 2025-09-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0018_session_teacher_payment_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="guardian_phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="رقم هاتف الولي"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="رقم هاتف الطالب"
            ),
        ),
    ]
