# Generated by Django 5.0.7 on 2025-09-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0019_alter_student_guardian_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='تسجيل مجاني'),
        ),
    ]