# Generated by Django 4.2.7 on 2024-03-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0019_alter_student_guardian_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='فوج مجاني'),
        ),
    ]
