# Generated by Django 4.2.7 on 2024-03-22 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0020_studentgroup_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='status',
            field=models.CharField(choices=[('active', 'مستمر'), ('stopped', 'متوقف')], default='active', max_length=10, verbose_name='حالة التسجيل'),
        ),
        migrations.CreateModel(
            name='StudentGroupSuspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاريخ بداية التوقف')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ استئناف الدراسة')),
                ('student_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspensions', to='school_app.studentgroup', verbose_name='تسجيل الطالب في الفوج')),
            ],
            options={
                'verbose_name': 'فترة توقف طالب',
                'verbose_name_plural': 'فترات توقف الطلاب',
                'ordering': ['-start_date'],
            },
        ),
    ]